### ISSUE TITLE
App crashes when toggling send button after taking picture

### ISSUE THREAD

**Issue by ghost** [WatchDoges/WatchDoge#127]
This issue should be fixed by PictureHandler.

Reason. toggleSendButton is called in updateUrisHashmap, which is called from PictureCreatingThread. Since toggleSendButton modifies the state of a view component in MainActivity's layout, a fatal exception is raised.

To replicate issue: Remove app from your phone. Launch it again. Fill in radiobuttons, title and description, take two pictures as fast as possible.

**Comment by ghost** [comment]
W/System.err: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
W/System.err:     at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6566)
W/System.err:     at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:946)
W/System.err:     at android.view.ViewGroup.invalidateChild(ViewGroup.java:5082)
W/System.err:     at android.view.View.invalidateInternal(View.java:12799)
W/System.err:     at android.view.View.invalidate(View.java:12763)
W/System.err:     at android.view.View.setEnabled(View.java:7541)
W/System.err:     at doge.watchdoge.activities.MainActivity.toggleSendButton(MainActivity.java:218)
W/System.err:     at doge.watchdoge.activities.MainActivity.updateUrisHashmap(MainActivity.java:266)
W/System.err:     at doge.watchdoge.imagehandlers.GpsPictureCreationThread.run(GpsPictureCreationThread.java:53)
I/System.out: Creating GPS Picture failed.
I/System.out: 3071 milliseconds to make picture
E/AndroidRuntime: FATAL EXCEPTION: Thread-33468
                  Process: doge.watchdoge, PID: 19897
                  android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                      at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6566)
                      at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:946)
                      at android.view.ViewGroup.invalidateChild(ViewGroup.java:5082)
                      at android.view.View.invalidateInternal(View.java:12799)
                      at android.view.View.invalidate(View.java:12763)
                      at android.view.View.invalidateViewProperty(View.java:12883)
                      at android.view.View.setAlpha(View.java:11541)
                      at doge.watchdoge.activities.MainActivity.toggleSendButton(MainActivity.java:220)
                      at doge.watchdoge.activities.MainActivity.updateUrisHashmap(MainActivity.java:266)
                      at doge.watchdoge.imagehandlers.PictureCreationThread.run(PictureCreationThread.java:37)
